image: registry.fedoraproject.org/fedora:latest

before_script:
  - dnf install -y make python3-pip python3-setuptools python3-pytest pylint

pylint:
  stage: build
  script:
    - make pylint

install:
  stage: build
  script:
    - make install
    - ovmfctl --help
    - ovmfdump --help
