image: registry.fedoraproject.org/fedora:latest

before_script:
  - dnf install -y make python3-pip python3-setuptools python3-cryptography python3-pytest pylint edk2-aarch64 edk2-ovmf tree
  - export PATH="${PATH}:${HOME}/.local/bin"

pylint:
  script:
    - make pylint

ovmfctl:
  script:
    - make install
    - make test-ovmfctl

ovmfdump:
  script:
    - make install
    - make test-ovmfdump

package:
  script:
    - dnf install -y fedora-packager pyp2rpm createrepo python3-devel python3-build twine
    - make package
  artifacts:
    paths:
      - dist
      - rpms

pages:
  stage: deploy
  dependencies:
    - package
  only:
    - tags
  script:
    - mkdir public
    - mv dist rpms public
    - tree -T "$CI_PROJECT_NAME rpms" --charset utf8 -H . public > index.html
    - mv index.html public
  artifacts:
    paths:
      - public/
