image: registry.fedoraproject.org/fedora:latest

before_script:
  - dnf install -y make python3-pip python3-setuptools python3-cryptography python3-pytest pylint edk2-aarch64 edk2-ovmf tree
  - export PATH="${PATH}:${HOME}/.local/bin"

pylint:
  script:
    - make pylint

ovmfctl:
  script:
    - make install
    - ovmfctl --help
    - ovmfctl -i /usr/share/OVMF/OVMF_VARS.secboot.fd --print --hexdump
    - ovmfctl -i /usr/share/OVMF/OVMF_VARS.fd -o vars.fd --enroll-redhat --secure-boot

ovmfdump:
  script:
    - make install
    - ovmfdump --help
    - ovmfdump -i /usr/share/edk2/aarch64/QEMU_EFI.fd
    - ovmfdump -i /usr/share/edk2/aarch64/QEMU_VARS.fd
    - ovmfdump -i /usr/share/OVMF/OVMF_CODE.secboot.fd
    - ovmfdump -i /usr/share/OVMF/OVMF_VARS.secboot.fd

package:
  script:
    - dnf install -y fedora-packager pyp2rpm createrepo python3-devel
    - make package
  artifacts:
    paths:
      - rpms

pages:
  stage: deploy
  script:
    - tree -T "$CI_PROJECT_NAME rpms" --charset utf8 -H . rpms > index.html
    - mv index.html rpms
  artifacts:
    paths:
      - rpms/
