image: registry.fedoraproject.org/fedora:latest

before_script:
  - dnf install -y make python3-pip python3-setuptools python3-cryptography python3-pytest pylint edk2-aarch64 edk2-ovmf kernel-core
  - export PATH="${PATH}:${HOME}/.local/bin"

pylint:
  script:
    - make pylint

ovmfctl:
  script:
    - make install
    - ovmfctl --help
    - ovmfctl -i /usr/share/OVMF/OVMF_VARS.secboot.fd -o vars.fd -p -x
    - GUID="a0baa8a3-041d-48a8-bc87-c36d121b5e3d"
    - CERT="$(rpm -ql kernel-core | grep kernel-signing-ca.cer | head -1)"
    - ls -l $CERT
    - ovmfctl -i vars.fd -o vars.fd --add-db $GUID $CERT -p

ovmfdump:
  script:
    - make install
    - ovmfdump --help
    - ovmfdump -i /usr/share/edk2/aarch64/QEMU_EFI.fd
    - ovmfdump -i /usr/share/edk2/aarch64/QEMU_VARS.fd
    - ovmfdump -i /usr/share/OVMF/OVMF_CODE.secboot.fd
    - ovmfdump -i /usr/share/OVMF/OVMF_VARS.secboot.fd
