image: registry.fedoraproject.org/fedora:latest

before_script:
  - dnf install -y make python3-pip python3-setuptools python3-devel python3-cryptography edk2-ovmf tree diffutils gcc
  - dnf install -y edk2-aarch64 || true # optional
  - pip3 install --user crc32c pylint build twine
  - export PATH="${PATH}:${HOME}/.local/bin"

package:
  stage: build
  script:
    - dnf install -y fedora-packager pyp2rpm createrepo
    - make dist rpms
  artifacts:
    paths:
      - dist
      - rpms

.testscript: &testscript
  - make test-dump
  - make test-vars
  - make test-sigdb
  - make test-unittest

pylint:
  stage: test
  script:
    - make install
    - make pylint

test-fedora:
  stage: test
  script:
    - make install
    - *testscript

test-centos8:
  stage: test
  image: quay.io/centos/centos:stream8
  script:
    - make install
    - *testscript

test-centos9:
  stage: test
  image: quay.io/centos/centos:stream9
  script:
    - make install
    - *testscript

test-rpm:
  stage: test
  dependencies:
    - package
  before_script:
  script:
    - dnf install -y rpms/noarch/*.noarch.rpm
    - *testscript

pages:
  stage: deploy
  dependencies:
    - package
  only:
    - tags
  script:
    - mkdir public
    - mv dist rpms public
    - tree -T "$CI_PROJECT_NAME rpms" --charset utf8 -H . public > index.html
    - mv index.html public
  artifacts:
    paths:
      - public/

twine:
  stage: deploy
  image: python:latest
  dependencies:
    - package
  only:
    - tags
  script:
    - pip install twine
    - ls -l dist
    - python -m twine check dist/*
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
