image: registry.fedoraproject.org/fedora:latest

before_script:
  - dnf install -y make python3-pip python3-setuptools python3-cryptography edk2-ovmf tree diffutils
  - dnf install -y edk2-aarch64 || true # optional
  - pip3 install --user pylint crc32c
  - export PATH="${PATH}:${HOME}/.local/bin"

pylint:
  script:
    - make pylint

package:
  script:
    - dnf install -y fedora-packager pyp2rpm createrepo python3-devel python3-build twine
    - make package
  artifacts:
    paths:
      - dist
      - rpms

.testscript: &testscript
  - make install
  - make test-ovmfctl
  - make test-ovmfdump
  - make test-unittest

test-fedora:
  script:
    - *testscript

test-centos8:
  image: quay.io/centos/centos:stream8
  script:
    - *testscript

pages:
  stage: deploy
  dependencies:
    - package
  only:
    - tags
  script:
    - mkdir public
    - mv dist rpms public
    - tree -T "$CI_PROJECT_NAME rpms" --charset utf8 -H . public > index.html
    - mv index.html public
  artifacts:
    paths:
      - public/
